vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO asfernandes/fb-cpp
    REF v1.0.0
    SHA512 3955dcbee777d9e97618fe82cfbfc495671a1abf28573c7232aba9bb25a454ff2755cd5e8d2ad19bead105728b2e1dcf36f9bb0a6a317b3fddc1160e746988ca
    HEAD_REF main
)

set(FB_CPP_USE_BOOST_DLL_VALUE 0)
set(FB_CPP_USE_BOOST_DLL_OPTION OFF)
if("boost-dll" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_DLL_VALUE 1)
    set(FB_CPP_USE_BOOST_DLL_OPTION ON)
endif()

set(FB_CPP_USE_BOOST_MULTIPRECISION_VALUE 0)
set(FB_CPP_USE_BOOST_MULTIPRECISION_OPTION OFF)
if("boost-multiprecision" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_MULTIPRECISION_VALUE 1)
    set(FB_CPP_USE_BOOST_MULTIPRECISION_OPTION ON)
endif()

set(FB_CPP_USE_BOOST_DECIMAL_VALUE 0)
set(FB_CPP_USE_BOOST_DECIMAL_OPTION OFF)
if("boost-decimal" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_DECIMAL_VALUE 1)
    set(FB_CPP_USE_BOOST_DECIMAL_OPTION ON)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_TESTING=OFF
        -DFB_CPP_USE_BOOST_DLL=${FB_CPP_USE_BOOST_DLL_OPTION}
        -DFB_CPP_USE_BOOST_MULTIPRECISION=${FB_CPP_USE_BOOST_MULTIPRECISION_OPTION}
        -DFB_CPP_USE_BOOST_DECIMAL=${FB_CPP_USE_BOOST_DECIMAL_OPTION}
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(CONFIG_PATH "fb-cpp/cmake/${PORT}")

file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/share/${PORT}")
configure_file(
    "${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake.in"
    "${CURRENT_PACKAGES_DIR}/share/${PORT}/vcpkg-cmake-wrapper.cmake"
    @ONLY
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
