vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO asfernandes/fb-cpp
    REF v0.0.6
    SHA512 b414ecea83b3874aa39ddbdaded5f3357ce97b5855a4adcb9c6afbad2ecc8421aadb64ca7506799ecbddeba411e7828e247c35d29769c256dc1d70c0393a6f42
    HEAD_REF main
)

set(FB_CPP_USE_BOOST_DLL_VALUE 0)
set(FB_CPP_USE_BOOST_DLL_OPTION OFF)
if("boost-dll" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_DLL_VALUE 1)
    set(FB_CPP_USE_BOOST_DLL_OPTION ON)
endif()

set(FB_CPP_USE_BOOST_MULTIPRECISION_VALUE 0)
set(FB_CPP_USE_BOOST_MULTIPRECISION_OPTION OFF)
if("boost-multiprecision" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_MULTIPRECISION_VALUE 1)
    set(FB_CPP_USE_BOOST_MULTIPRECISION_OPTION ON)
endif()

set(FB_CPP_USE_BOOST_DECIMAL_VALUE 0)
set(FB_CPP_USE_BOOST_DECIMAL_OPTION OFF)
if("boost-decimal" IN_LIST FEATURES)
    set(FB_CPP_USE_BOOST_DECIMAL_VALUE 1)
    set(FB_CPP_USE_BOOST_DECIMAL_OPTION ON)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_TESTING=OFF
        -DFB_CPP_USE_BOOST_DLL=${FB_CPP_USE_BOOST_DLL_OPTION}
        -DFB_CPP_USE_BOOST_MULTIPRECISION=${FB_CPP_USE_BOOST_MULTIPRECISION_OPTION}
        -DFB_CPP_USE_BOOST_DECIMAL=${FB_CPP_USE_BOOST_DECIMAL_OPTION}
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(CONFIG_PATH "fb-cpp/cmake/${PORT}")

file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/share/${PORT}")
configure_file(
    "${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake.in"
    "${CURRENT_PACKAGES_DIR}/share/${PORT}/vcpkg-cmake-wrapper.cmake"
    @ONLY
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
